### ISSUE TITLE
vbox freezing issue

### ISSUE THREAD

**Issue by SvenDowideit** [unclejack/debian2docker#37]
I've seen the vm freeze quite a bit, just like b2d did. we changed the kernel to CONFIG_HZ=100

but further reading makes me wonder if https://blogs.oracle.com/fatbloke/entry/speeding_up_your_linux_guests has a better answer.

**Comment by unclejack** [comment]
It looks like VirtualBox isn't being developed as it once was and there aren't that many changes being made to its code any more.

If this is still a problem, it's most likely not something which can be fixed without putting a lot of time into this and having a large team work on VirtualBox itself.

I'll close this issue because there's not much we can do or hope to aid someone else do.
